# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - imagenesaleatorias

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2318102998c648ab81ebf9282c92912f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7e4f95b50bd04c7d800c1f61f0ef2c2b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2318102998c648ab81ebf9282c92912f }}/imagenesaleaorias:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'imagenesaleatorias'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c56d83b4855141e68ef6c85e3ffd7187 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2318102998c648ab81ebf9282c92912f }}/imagenesaleaorias:${{ github.sha }}'